DROP TABLE IF EXISTS daily_insights;
DROP TABLE IF EXISTS words;
DROP TABLE IF EXISTS user_settings;

-- users table assumed to exist already

CREATE TABLE user_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE,
    language_code VARCHAR(8) NOT NULL DEFAULT 'en',
    theme_mode VARCHAR(16) NOT NULL DEFAULT 'AUTO',
    notifications_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    review_reminders BOOLEAN NOT NULL DEFAULT TRUE,
    motivational_messages BOOLEAN NOT NULL DEFAULT TRUE,
    daily_reminder_time VARCHAR(8) NOT NULL DEFAULT '18:00',
    minimum_due_cards INT NOT NULL DEFAULT 5,
    successes_to_advance INT NOT NULL DEFAULT 1,
    forgot_penalty INT NOT NULL DEFAULT 2
);

CREATE TABLE words (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    original_word TEXT NOT NULL,
    translation TEXT NOT NULL,
    description TEXT,
    level INT NOT NULL DEFAULT 0,
    ease_factor REAL NOT NULL DEFAULT 2.5,
    review_interval INT NOT NULL DEFAULT 0,
    repetitions INT NOT NULL DEFAULT 0,
    last_review_date BIGINT NOT NULL DEFAULT 0,
    next_review_date BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE daily_insights (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    insight_text VARCHAR(500) NOT NULL,
    generated_at TIMESTAMP NOT NULL,
    date VARCHAR(10) NOT NULL,
    sent_via_push BOOLEAN NOT NULL DEFAULT FALSE,
    push_sent_at TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_words_user_id ON words(user_id);
CREATE INDEX IF NOT EXISTS idx_words_level ON words(level);
CREATE INDEX IF NOT EXISTS idx_daily_insights_user_id ON daily_insights(user_id);
CREATE INDEX IF NOT EXISTS idx_daily_insights_date ON daily_insights(date);
CREATE INDEX IF NOT EXISTS idx_daily_insights_user_date ON daily_insights(user_id, date);

