-- H2 compatibility: PostgreSQL's TO_TIMESTAMP(epoch_seconds) is not built-in
CREATE ALIAS IF NOT EXISTS TO_TIMESTAMP FOR "com.alirezaiyan.vokab.server.H2CompatFunctions.toTimestamp";

DROP TABLE IF EXISTS word_rush_games;
DROP TABLE IF EXISTS review_events;
DROP TABLE IF EXISTS study_sessions;
DROP TABLE IF EXISTS refresh_tokens;
DROP TABLE IF EXISTS push_tokens;
DROP TABLE IF EXISTS user_platforms;
DROP TABLE IF EXISTS daily_activities;
DROP TABLE IF EXISTS daily_insights;
DROP TABLE IF EXISTS words;
DROP TABLE IF EXISTS user_settings;
DROP TABLE IF EXISTS subscriptions;
DROP TABLE IF EXISTS users;

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    google_id VARCHAR(255) UNIQUE,
    apple_id VARCHAR(255) UNIQUE,
    profile_image_url VARCHAR(512),
    display_alias VARCHAR(50),
    revenuecat_user_id VARCHAR(255) UNIQUE,
    subscription_status VARCHAR(32) NOT NULL DEFAULT 'FREE',
    subscription_expires_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_login_at TIMESTAMP,
    current_streak INT NOT NULL DEFAULT 0,
    longest_streak INT NOT NULL DEFAULT 0,
    ai_extraction_usage_count INT NOT NULL DEFAULT 0,
    first_word_added_at TIMESTAMP,
    first_review_at TIMESTAMP,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    signup_country VARCHAR(2),
    last_login_country VARCHAR(2)
);

CREATE TABLE push_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    token VARCHAR(512) NOT NULL UNIQUE,
    platform VARCHAR(16) NOT NULL,
    device_id VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_push_token ON push_tokens(token);

CREATE TABLE user_platforms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    platform VARCHAR(20) NOT NULL,
    first_seen_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_seen_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    app_version VARCHAR(32),
    CONSTRAINT uq_user_platform UNIQUE (user_id, platform),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_user_platforms_user_id ON user_platforms(user_id);

CREATE TABLE user_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE,
    language_code VARCHAR(8) NOT NULL DEFAULT 'en',
    theme_mode VARCHAR(16) NOT NULL DEFAULT 'AUTO',
    notifications_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    review_reminders_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    motivational_messages BOOLEAN NOT NULL DEFAULT TRUE,
    daily_reminder_time VARCHAR(8) NOT NULL DEFAULT '18:00',
    notification_frequency VARCHAR(32) NOT NULL DEFAULT 'DAILY',
    minimum_due_cards INT NOT NULL DEFAULT 5,
    successes_to_advance INT NOT NULL DEFAULT 1,
    forgot_penalty INT NOT NULL DEFAULT 2,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE words (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    original_word TEXT NOT NULL,
    translation TEXT NOT NULL,
    description TEXT,
    source_language VARCHAR(10) NOT NULL,
    target_language VARCHAR(10) NOT NULL,
    level INT NOT NULL DEFAULT 0,
    ease_factor REAL NOT NULL DEFAULT 2.5,
    review_interval INT NOT NULL DEFAULT 0,
    repetitions INT NOT NULL DEFAULT 0,
    last_review_date BIGINT NOT NULL DEFAULT 0,
    next_review_date BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_words_user_id ON words(user_id);
CREATE INDEX IF NOT EXISTS idx_words_level ON words(level);

CREATE TABLE daily_insights (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    insight_text VARCHAR(500) NOT NULL,
    generated_at TIMESTAMP NOT NULL,
    date VARCHAR(10) NOT NULL,
    sent_via_push BOOLEAN NOT NULL DEFAULT FALSE,
    push_sent_at TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT uq_daily_insights_user_date UNIQUE (user_id, date)
);

CREATE INDEX IF NOT EXISTS idx_daily_insights_user_id ON daily_insights(user_id);
CREATE INDEX IF NOT EXISTS idx_daily_insights_date ON daily_insights(date);
CREATE INDEX IF NOT EXISTS idx_daily_insights_user_date ON daily_insights(user_id, date);

CREATE TABLE daily_activities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    activity_date DATE NOT NULL,
    review_count INT NOT NULL DEFAULT 1,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_daily_activity UNIQUE (user_id, activity_date),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_user_activity_date ON daily_activities(user_id, activity_date);

CREATE TABLE subscriptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    revenuecat_subscription_id VARCHAR(255) UNIQUE,
    product_id VARCHAR(255) NOT NULL,
    status VARCHAR(32) NOT NULL,
    started_at TIMESTAMP NOT NULL,
    expires_at TIMESTAMP,
    cancelled_at TIMESTAMP,
    is_trial BOOLEAN NOT NULL DEFAULT FALSE,
    auto_renew BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE refresh_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token_hash VARCHAR(255) NOT NULL UNIQUE,
    user_id BIGINT NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    revoked BOOLEAN NOT NULL DEFAULT FALSE,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_refresh_tokens_user_id ON refresh_tokens(user_id);
CREATE INDEX IF NOT EXISTS idx_refresh_tokens_hash ON refresh_tokens(token_hash);
CREATE INDEX IF NOT EXISTS idx_refresh_tokens_expires_at ON refresh_tokens(expires_at);

-- Analytics tables
CREATE TABLE study_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    client_session_id TEXT NOT NULL,
    started_at BIGINT NOT NULL,
    ended_at BIGINT,
    duration_ms BIGINT NOT NULL DEFAULT 0,
    total_cards INT NOT NULL DEFAULT 0,
    correct_count INT NOT NULL DEFAULT 0,
    incorrect_count INT NOT NULL DEFAULT 0,
    review_type TEXT NOT NULL DEFAULT 'REVIEW',
    completed_normally BOOLEAN NOT NULL DEFAULT TRUE,
    source_language TEXT,
    target_language TEXT,
    trigger_source TEXT NOT NULL DEFAULT 'unknown',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_session_user_client UNIQUE (user_id, client_session_id),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE review_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    word_id BIGINT NOT NULL,
    word_text TEXT NOT NULL DEFAULT '',
    word_translation TEXT NOT NULL DEFAULT '',
    source_language TEXT NOT NULL DEFAULT '',
    target_language TEXT NOT NULL DEFAULT '',
    rating INT NOT NULL,
    previous_level INT NOT NULL,
    new_level INT NOT NULL,
    response_time_ms BIGINT NOT NULL DEFAULT 0,
    reviewed_at BIGINT NOT NULL,
    FOREIGN KEY (session_id) REFERENCES study_sessions(id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_study_sessions_user ON study_sessions(user_id);
CREATE INDEX IF NOT EXISTS idx_review_events_user ON review_events(user_id);
CREATE INDEX IF NOT EXISTS idx_review_events_session ON review_events(session_id);
CREATE INDEX IF NOT EXISTS idx_review_events_word ON review_events(user_id, word_id);
CREATE INDEX IF NOT EXISTS idx_review_events_reviewed_at ON review_events(user_id, reviewed_at);
CREATE INDEX IF NOT EXISTS idx_review_events_level ON review_events(user_id, previous_level);
CREATE INDEX IF NOT EXISTS idx_review_events_new_level ON review_events(user_id, new_level);

-- Word Rush tables
CREATE TABLE word_rush_games (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id           BIGINT    NOT NULL,
    client_game_id    TEXT      NOT NULL,
    score             INT       NOT NULL DEFAULT 0,
    total_questions   INT       NOT NULL DEFAULT 0,
    correct_count     INT       NOT NULL DEFAULT 0,
    best_streak       INT       NOT NULL DEFAULT 0,
    duration_ms       BIGINT    NOT NULL DEFAULT 0,
    avg_response_ms   BIGINT    NOT NULL DEFAULT 0,
    grade             TEXT      NOT NULL DEFAULT 'D',
    lives_remaining   INT       NOT NULL DEFAULT 0,
    completed_normally BOOLEAN  NOT NULL DEFAULT FALSE,
    played_at         BIGINT    NOT NULL,
    created_at        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_word_rush_user_game UNIQUE (user_id, client_game_id),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_word_rush_user ON word_rush_games(user_id);
CREATE INDEX IF NOT EXISTS idx_word_rush_user_played ON word_rush_games(user_id, played_at DESC);
CREATE INDEX IF NOT EXISTS idx_word_rush_user_streak ON word_rush_games(user_id, best_streak DESC);
