-- Migrate refresh_tokens table to support token rotation and device tracking.
-- This migration handles both new installations and existing production databases.

-- Create table if it doesn't exist (for new installations)
CREATE TABLE IF NOT EXISTS refresh_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    revoked_at TIMESTAMP,
    revoked BOOLEAN NOT NULL DEFAULT FALSE,
    replaced_by BIGINT,
    CONSTRAINT fk_refresh_tokens_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- Add token_hash column if it doesn't exist (may be named 'token' in old schema)
DO $$
BEGIN
    -- Only proceed if table exists
    IF EXISTS (
        SELECT 1 FROM information_schema.tables 
        WHERE table_name = 'refresh_tokens'
    ) THEN
        IF NOT EXISTS (
            SELECT 1 FROM information_schema.columns 
            WHERE table_name = 'refresh_tokens' AND column_name = 'token_hash'
        ) THEN
            -- Check if old 'token' column exists and rename it
            IF EXISTS (
                SELECT 1 FROM information_schema.columns 
                WHERE table_name = 'refresh_tokens' AND column_name = 'token'
            ) THEN
                ALTER TABLE refresh_tokens RENAME COLUMN token TO token_hash;
            ELSE
                -- Add new token_hash column (nullable initially, will be populated by application)
                ALTER TABLE refresh_tokens 
                ADD COLUMN token_hash VARCHAR(255);
            END IF;
        END IF;
        
        -- Add unique constraint if it doesn't exist and column exists
        IF EXISTS (
            SELECT 1 FROM information_schema.columns 
            WHERE table_name = 'refresh_tokens' AND column_name = 'token_hash'
        ) AND NOT EXISTS (
            SELECT 1 FROM pg_constraint 
            WHERE conname = 'refresh_tokens_token_hash_key'
        ) THEN
            ALTER TABLE refresh_tokens 
            ADD CONSTRAINT refresh_tokens_token_hash_key UNIQUE (token_hash);
        END IF;
    END IF;
END $$;

-- Add family_id column (required for token rotation)
ALTER TABLE refresh_tokens
    ADD COLUMN IF NOT EXISTS family_id VARCHAR(64);

-- Update existing rows to have a default family_id if they don't have one
-- This ensures backward compatibility with existing tokens
UPDATE refresh_tokens
SET family_id = 'legacy-' || id::text
WHERE family_id IS NULL;

-- Make family_id NOT NULL after setting defaults
ALTER TABLE refresh_tokens
    ALTER COLUMN family_id SET NOT NULL;

-- Add replaced_by column if it doesn't exist (for token rotation)
ALTER TABLE refresh_tokens
    ADD COLUMN IF NOT EXISTS replaced_by BIGINT;

-- Add optional metadata columns for device tracking
ALTER TABLE refresh_tokens
    ADD COLUMN IF NOT EXISTS device_id VARCHAR(255);

ALTER TABLE refresh_tokens
    ADD COLUMN IF NOT EXISTS user_agent VARCHAR(512);

ALTER TABLE refresh_tokens
    ADD COLUMN IF NOT EXISTS ip_address VARCHAR(45);

-- Create indexes only if they don't exist
CREATE INDEX IF NOT EXISTS idx_refresh_tokens_user_id ON refresh_tokens(user_id);
CREATE INDEX IF NOT EXISTS idx_refresh_tokens_family_id ON refresh_tokens(family_id);
CREATE INDEX IF NOT EXISTS idx_refresh_tokens_hash ON refresh_tokens(token_hash);
CREATE INDEX IF NOT EXISTS idx_refresh_tokens_expires_at ON refresh_tokens(expires_at);

