-- Comprehensive migration to ensure refresh_tokens table has all required columns
-- This migration is idempotent and safe to run multiple times
-- Handles both new installations and existing production databases

-- Step 1: Create table if it doesn't exist (for new installations)
CREATE TABLE IF NOT EXISTS refresh_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    revoked_at TIMESTAMP,
    revoked BOOLEAN NOT NULL DEFAULT FALSE,
    replaced_by BIGINT,
    CONSTRAINT fk_refresh_tokens_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- Step 2: Handle token_hash column (may be named 'token' in old schema)
DO $$
BEGIN
    -- Only proceed if table exists
    IF EXISTS (
        SELECT 1 FROM information_schema.tables 
        WHERE table_name = 'refresh_tokens'
    ) THEN
        -- Check if token_hash column exists
        IF NOT EXISTS (
            SELECT 1 FROM information_schema.columns 
            WHERE table_name = 'refresh_tokens' AND column_name = 'token_hash'
        ) THEN
            -- Check if old 'token' column exists and rename it
            IF EXISTS (
                SELECT 1 FROM information_schema.columns 
                WHERE table_name = 'refresh_tokens' AND column_name = 'token'
            ) THEN
                ALTER TABLE refresh_tokens RENAME COLUMN token TO token_hash;
            ELSE
                -- Add new token_hash column (nullable initially)
                ALTER TABLE refresh_tokens 
                ADD COLUMN token_hash VARCHAR(255);
            END IF;
        END IF;
        
        -- Add unique constraint on token_hash if it doesn't exist
        IF EXISTS (
            SELECT 1 FROM information_schema.columns 
            WHERE table_name = 'refresh_tokens' AND column_name = 'token_hash'
        ) AND NOT EXISTS (
            SELECT 1 FROM pg_constraint 
            WHERE conname = 'refresh_tokens_token_hash_key'
        ) THEN
            ALTER TABLE refresh_tokens 
            ADD CONSTRAINT refresh_tokens_token_hash_key UNIQUE (token_hash);
        END IF;
    END IF;
END $$;

-- Step 3: Add family_id column (required for token rotation)
ALTER TABLE refresh_tokens
    ADD COLUMN IF NOT EXISTS family_id VARCHAR(64);

-- Update existing rows to have a default family_id if they don't have one
UPDATE refresh_tokens
SET family_id = 'legacy-' || id::text
WHERE family_id IS NULL;

-- Make family_id NOT NULL after setting defaults (only if column exists and has no NULLs)
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_name = 'refresh_tokens' 
        AND column_name = 'family_id'
        AND is_nullable = 'YES'
    ) THEN
        -- Check if there are any NULL values
        IF NOT EXISTS (
            SELECT 1 FROM refresh_tokens WHERE family_id IS NULL
        ) THEN
            ALTER TABLE refresh_tokens
                ALTER COLUMN family_id SET NOT NULL;
        END IF;
    END IF;
END $$;

-- Step 4: Add revoked_at column if it doesn't exist
ALTER TABLE refresh_tokens
    ADD COLUMN IF NOT EXISTS revoked_at TIMESTAMP;

-- Step 5: Add created_at column if it doesn't exist
ALTER TABLE refresh_tokens
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- If created_at exists but is nullable, update existing rows and make it NOT NULL
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_name = 'refresh_tokens' 
        AND column_name = 'created_at'
        AND is_nullable = 'YES'
    ) THEN
        -- Set default for existing NULL rows
        UPDATE refresh_tokens
        SET created_at = CURRENT_TIMESTAMP
        WHERE created_at IS NULL;
        
        -- Make it NOT NULL
        ALTER TABLE refresh_tokens
            ALTER COLUMN created_at SET NOT NULL;
    END IF;
END $$;

-- Step 6: Add revoked column if it doesn't exist
ALTER TABLE refresh_tokens
    ADD COLUMN IF NOT EXISTS revoked BOOLEAN NOT NULL DEFAULT FALSE;

-- If revoked exists but is nullable, update existing rows and make it NOT NULL
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_name = 'refresh_tokens' 
        AND column_name = 'revoked'
        AND is_nullable = 'YES'
    ) THEN
        -- Set default for existing NULL rows
        UPDATE refresh_tokens
        SET revoked = FALSE
        WHERE revoked IS NULL;
        
        -- Make it NOT NULL
        ALTER TABLE refresh_tokens
            ALTER COLUMN revoked SET NOT NULL;
    END IF;
END $$;

-- Step 7: Add replaced_by column if it doesn't exist
ALTER TABLE refresh_tokens
    ADD COLUMN IF NOT EXISTS replaced_by BIGINT;

-- Step 8: Add optional metadata columns for device tracking
ALTER TABLE refresh_tokens
    ADD COLUMN IF NOT EXISTS device_id VARCHAR(255);

ALTER TABLE refresh_tokens
    ADD COLUMN IF NOT EXISTS user_agent VARCHAR(512);

ALTER TABLE refresh_tokens
    ADD COLUMN IF NOT EXISTS ip_address VARCHAR(45);

-- Step 9: Create all indexes (idempotent with IF NOT EXISTS)
CREATE INDEX IF NOT EXISTS idx_refresh_tokens_user_id ON refresh_tokens(user_id);
CREATE INDEX IF NOT EXISTS idx_refresh_tokens_family_id ON refresh_tokens(family_id);
CREATE INDEX IF NOT EXISTS idx_refresh_tokens_hash ON refresh_tokens(token_hash);
CREATE INDEX IF NOT EXISTS idx_refresh_tokens_expires_at ON refresh_tokens(expires_at);

